name: Pull Request
description: Pull request for an additional feature or a bug fix.
body:
- type: textarea
  attributes:
    label: Description
    description: >
      Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
  validations:
    required: true
- type: textarea
  attributes:
    label: How to verify the changes.
    description: >
      Tell us how to test and verify the status of the changes.
- type: textarea
  attributes:
    label: Screenshots (if applicable)
    value: >
      Thanks for contributing!
- type: markdown
  attributes:
    value: >
      Thanks for contributing!